semantic_identifiers:
  aliases:
    description: ''
  birthday:
    description: ''
  book_read_today:
    description: ''
  canonical_name:
    description: ''
  creator:
    description: ''
  dream_location:
    description: ''
  dream_lucidity:
    description: ''
  dream_motif:
    description: ''
  dream_motif_valence:
    description: ''
  entity:
    description: ''
  entity_type:
    description: ''
  first_met:
    description: ''
  format:
    description: ''
  hypnagogic_resonance:
    description: ''
  journal_entry_date:
    description: ''
  layer:
    description: ''
  note_type:
    description: ''
  origin:
    description: ''
  original_year_published:
    description: ''
  pillar:
    description: ''
  publish_studio:
    description: ''
  racing_thoughts_while_awake:
    description: ''
  ran_script_when_racing:
    description: ''
  reactivity:
    description: ''
  recall_ability:
    description: ''
  register:
    description: ''
  register_mode:
    description: ''
  relationship:
    description: ''
  tags:
    description: ''
  temporal_pace:
    description: ''
  title:
    description: ''
  unity_level:
    description: ''
  vector_direction:
    description: ''
