"""Retrieval inference, authority, execution, and hydration."""

from .control_plane import (
    ConformanceRequestResult,
    RetrievalConformanceError,
    RetrievalConformanceResult,
    conform_retrieval,
)
from .execution import (
    EXECUTION_CONTRACT_VERSION,
    RetrievalExecutionError,
    RetrievalExecutionRequestResult,
    RetrievalExecutionResult,
    execute_retrieval,
    load_retrieval_execution,
)
from .hydration import (
    HydratedCanonicalTarget,
    HydratedExactHit,
    HydratedExactResult,
    HydratedGraphDiscoveryHit,
    HydratedGraphDiscoveryResult,
    HydratedGraphOccurrence,
    HydratedGraphRelationResult,
    HydratedLexicalHit,
    HydratedLexicalResult,
    HydratedTemporalHit,
    HydratedTemporalResult,
    HydratedRequestResult,
    HydratedRetrievalResult,
    HydratedVectorHit,
    HydratedVectorResult,
    RetrievalHydrationError,
    hydrate_retrieval_execution,
)
from .inference import RetrievalInferenceResult, RuntimeRetrievalError, infer_retrieval
from .package import (
    IDENTITY_VERSION,
    RetrievalPackage,
    RetrievalPackageError,
    RetrievalPackageIdentity,
    load_retrieval_package,
    require_catalog_binding,
    require_current_package_identity,
)
from .package_verification import (
    VERIFICATION_CONTRACT_VERSION,
    RetrievalPackageInput,
    RetrievalPackageVerificationError,
    VerifiedRetrievalPackage,
    normalize_verified_retrieval_package,
    verify_retrieval_package,
)
from .packet import (
    PACKET_CONTRACT_VERSION, SELECTION_RULE_VERSION, CanonicalTargetPayload, CanonicalTargetRef,
    ExactOccurrence, GraphDiscoveryOccurrence, GraphRelationOccurrence, LexicalOccurrence,
    TemporalOccurrence,
    PacketAssemblyResult, PacketCoverage, PacketOccurrence, RemovalRecord, RequestCoverage,
    RetrievalPacket, RetrievalPacketError, VectorOccurrence, assemble_retrieval_packet,
)

__all__ = [
    "ConformanceRequestResult",
    "RetrievalConformanceError",
    "RetrievalConformanceResult",
    "conform_retrieval",
    "EXECUTION_CONTRACT_VERSION",
    "RetrievalExecutionError",
    "RetrievalExecutionRequestResult",
    "RetrievalExecutionResult",
    "execute_retrieval",
    "load_retrieval_execution",
    "HydratedCanonicalTarget",
    "HydratedExactHit",
    "HydratedExactResult",
    "HydratedGraphDiscoveryHit",
    "HydratedGraphDiscoveryResult",
    "HydratedGraphOccurrence",
    "HydratedGraphRelationResult",
    "HydratedLexicalHit",
    "HydratedLexicalResult",
    "HydratedTemporalHit",
    "HydratedTemporalResult",
    "HydratedRequestResult",
    "HydratedRetrievalResult",
    "HydratedVectorHit",
    "HydratedVectorResult",
    "RetrievalHydrationError",
    "hydrate_retrieval_execution",
    "RetrievalInferenceResult",
    "RuntimeRetrievalError",
    "infer_retrieval",
    "IDENTITY_VERSION",
    "RetrievalPackage",
    "RetrievalPackageError",
    "RetrievalPackageIdentity",
    "load_retrieval_package",
    "require_catalog_binding",
    "require_current_package_identity",
    "VERIFICATION_CONTRACT_VERSION",
    "RetrievalPackageInput",
    "RetrievalPackageVerificationError",
    "VerifiedRetrievalPackage",
    "normalize_verified_retrieval_package",
    "verify_retrieval_package",
    "PACKET_CONTRACT_VERSION", "SELECTION_RULE_VERSION", "RetrievalPacketError",
    "CanonicalTargetRef", "CanonicalTargetPayload", "PacketOccurrence", "ExactOccurrence",
    "LexicalOccurrence", "TemporalOccurrence", "VectorOccurrence", "GraphDiscoveryOccurrence", "GraphRelationOccurrence",
    "RequestCoverage", "PacketCoverage", "RemovalRecord", "RetrievalPacket", "PacketAssemblyResult",
    "assemble_retrieval_packet",
]
