"""Deterministic retrieval inference, package, execution, and hydration."""

from .control_plane import (
    ConformanceRequestResult,
    RetrievalConformanceError,
    RetrievalConformanceResult,
    conform_retrieval,
)
from .execution import (
    EXECUTION_CONTRACT_VERSION,
    RetrievalExecutionError,
    RetrievalExecutionRequestResult,
    RetrievalExecutionResult,
    execute_retrieval,
    load_retrieval_execution,
)
from .hydration import (
    HydratedCanonicalTarget,
    HydratedExactHit,
    HydratedExactResult,
    HydratedGraphDiscoveryHit,
    HydratedGraphDiscoveryResult,
    HydratedGraphOccurrence,
    HydratedGraphRelationResult,
    HydratedLexicalHit,
    HydratedLexicalResult,
    HydratedRequestResult,
    HydratedRetrievalResult,
    HydratedVectorHit,
    HydratedVectorResult,
    RetrievalHydrationError,
    hydrate_retrieval_execution,
)
from .inference import RetrievalInferenceResult, RuntimeRetrievalError, infer_retrieval
from .package import (
    IDENTITY_VERSION,
    RetrievalPackage,
    RetrievalPackageError,
    RetrievalPackageIdentity,
    load_retrieval_package,
    require_catalog_binding,
    require_current_package_identity,
)
from .package_verification import (
    VERIFICATION_CONTRACT_VERSION,
    RetrievalPackageVerificationError,
    VerifiedRetrievalPackage,
    verify_retrieval_package,
)

__all__ = [
    "ConformanceRequestResult",
    "RetrievalConformanceError",
    "RetrievalConformanceResult",
    "conform_retrieval",
    "EXECUTION_CONTRACT_VERSION",
    "RetrievalExecutionError",
    "RetrievalExecutionRequestResult",
    "RetrievalExecutionResult",
    "execute_retrieval",
    "load_retrieval_execution",
    "HydratedCanonicalTarget",
    "HydratedExactHit",
    "HydratedExactResult",
    "HydratedGraphDiscoveryHit",
    "HydratedGraphDiscoveryResult",
    "HydratedGraphOccurrence",
    "HydratedGraphRelationResult",
    "HydratedLexicalHit",
    "HydratedLexicalResult",
    "HydratedRequestResult",
    "HydratedRetrievalResult",
    "HydratedVectorHit",
    "HydratedVectorResult",
    "RetrievalHydrationError",
    "hydrate_retrieval_execution",
    "RetrievalInferenceResult",
    "RuntimeRetrievalError",
    "infer_retrieval",
    "IDENTITY_VERSION",
    "RetrievalPackage",
    "RetrievalPackageError",
    "RetrievalPackageIdentity",
    "load_retrieval_package",
    "require_catalog_binding",
    "require_current_package_identity",
    "VERIFICATION_CONTRACT_VERSION",
    "RetrievalPackageVerificationError",
    "VerifiedRetrievalPackage",
    "verify_retrieval_package",
]
